##THYMELEAF DEVELOP
spring:
  thymeleaf:
    cache: false

  jpa:
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      file-size-threshold: 2KB

logging:
  level:
    org.springframework: info
    io.github.benkoff.webrtcss: debug

file:
  upload-dir: /var/www/uploads
#  upload-dir: C:\dorma