##THYMELEAF DEVELOP
spring:
  thymeleaf:
    cache: false

  jpa:
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.springframework: info
    io.github.benkoff.webrtcss: debug